eureka:
  instance:
    hostname: komentet
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
server:
  port: 8071
spring:
  profiles:
    active: docker
  application:
    name: komentet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_komentet:5432/komentet
    username: postgres
    password: dren123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    users-url: http://users:8111/api/v1/user