eureka:
  instance:
    name: users
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8111
spring:
  profiles:
    active: docker
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_users:5432/users
    username: postgres
    password: dren123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect