eureka:
  instance:
    hostname: komentet
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8071
spring:
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
  application:
    name: komentet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/komentet
    username: postgres
    password: dren123
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: prometheus

application:
  config:
    users-url: http://localhost:8111/api/v1/user