eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: komentet
          uri: http://localhost:8071
          predicates:
            - Path = /api/v1/komentet/**

        - id: lajmet
          uri: http://localhost:8090
          predicates:
            - Path = /api/v1/lajmet/**
    config:
      import: optional:configserver:http://localhost:8888
server:
  port: 8222