eureka:
  client:
    enabled: false
  server:
    enabled: false

spring:
  profiles:
    active: native
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    discovery:
      locator:
        enabled: false
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: komentet
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/komentet/**

        - id: komentiNoAuth
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/komenti/noAuth/**

        - id: lajmet
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/lajmet/**

        - id: ankesat
          uri: http://localhost:8061
          predicates:
            - Path=/api/v1/ankesa/**

        - id: auth
          uri: http://localhost:8111
          predicates:
            - Path=/api/v1/auth/**

        - id: users
          uri: http://localhost:8111
          predicates:
            - Path=/api/v1/user/**

        - id: adminUser
          uri: http://localhost:8111
          predicates:
            - Path=/api/v1/admin/**

        - id: adminLajmi
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/adminLajmi/**

        - id: autori
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/autori/**

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus

server:
  port: 8222

security:
  secret:
    key: "598CCC87F435776673862D86F8B93B2B67A0C2CEA75F91CF89A285D971E7C12F"