eureka:
  client:
    enabled: false
  server:
    enabled: false

spring:
  application:
    name: gateway
  cloud:
    discovery:
      locator:
        enabled: false
    config:
      enabled: false
    redis:
      host: redis
      port: 6379
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: komentet
          uri: http://komentet:8071
          predicates:
            - Path=/api/v1/komentet/**

        - id: komentiNoAuth
          uri: http://komentet:8071
          predicates:
            - Path=/api/v1/komenti/noAuth/**

        - id: lajmet
          uri: http://lajmet:8090
          predicates:
            - Path=/api/v1/lajmet/**

        - id: ankesat
          uri: http://ankesat:8061
          predicates:
            - Path=/api/v1/ankesa/**

        - id: auth
          uri: http://users:8111
          predicates:
            - Path=/api/v1/auth/**

        - id: users
          uri: http://users:8111
          predicates:
            - Path=/api/v1/user/**

        - id: adminUser
          uri: http://users:8111
          predicates:
            - Path=/api/v1/admin/**

        - id: adminLajmi
          uri: http://lajmet:8090
          predicates:
            - Path=/api/v1/adminLajmi/**

        - id: autori
          uri: http://lajmet:8090
          predicates:
            - Path=/api/v1/autori/**

server:
  port: 8222

security:
  secret:
    key: "598CCC87F435776673862D86F8B93B2B67A0C2CEA75F91CF89A285D971E7C12F"