eureka:
  client:
    enabled: false
  server:
    enabled: false

spring:
  application:
    name: gateway
  cloud:
    discovery:
      locator:
        enabled: false
    config:
      enabled: false
    redis:
      host: redis
      port: 6379
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: komentet
          uri: http://komentet:8071
          predicates:
            - Path=/api/v1/komentet/**

        - id: lajmet
          uri: http://lajmet:8090
          predicates:
            - Path=/api/v1/lajmet/**

        - id: ankesat
          uri: http://ankesat:8061
          predicates:
            - Path=/api/v1/ankesa/**

        - id: users
          uri: http://localhost:8111
          predicates:
            - Path=/api/v1/user/**
            - Path=/api/v1/auth/**

server:
  port: 8222