eureka:
  client:
    enabled: false
  server:
    enabled: false

spring:
  profiles:
    active: native
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    discovery:
      locator:
        enabled: false
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: komentet
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/komentet/**

        - id: lajmet
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/lajmet/**

        - id: ankesat
          uri: http://localhost:8061
          predicates:
            - Path=/api/v1/ankesa/**
server:
  port: 8222