eureka:
  client:
    enabled: false
  server:
    enabled: false

spring:
  application:
    name: gateway
  cloud:
    discovery:
      locator:
        enabled: false
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: komentet
          uri: http://komentet:8071
          predicates:
            - Path=/api/v1/komentet/**

        - id: lajmet
          uri: http://lajmet:8090
          predicates:
            - Path=/api/v1/lajmet/**
server:
  port: 8222